# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Ariff\Documentos\Visual Codex\Proyecto uni\proyecto lenguaje expresivo\ventanas\calificar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_15 = QtWidgets.QWidget(self.widget_3)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelreproductor_3 = QtWidgets.QLabel(self.widget_15)
        self.labelreproductor_3.setStyleSheet("font: 12pt \"Arial Rounded MT Bold\";")
        self.labelreproductor_3.setObjectName("labelreproductor_3")
        self.horizontalLayout_2.addWidget(self.labelreproductor_3)
        self.calificacion = QtWidgets.QLabel(self.widget_15)
        self.calificacion.setStyleSheet("font: 100pt \"Arial Rounded MT Bold\";")
        self.calificacion.setText("")
        self.calificacion.setObjectName("calificacion")
        self.horizontalLayout_2.addWidget(self.calificacion)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_8.addWidget(self.widget_15)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labeltxtoleer_3 = QtWidgets.QLabel(self.widget_7)
        self.labeltxtoleer_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labeltxtoleer_3.setStyleSheet("font: 12pt \"Arial Rounded MT Bold\";")
        self.labeltxtoleer_3.setText("")
        self.labeltxtoleer_3.setObjectName("labeltxtoleer_3")
        self.verticalLayout_9.addWidget(self.labeltxtoleer_3)
        self.verticalLayout_7.addWidget(self.widget_7)
        self.btnregresar = QtWidgets.QPushButton(self.widget_4)
        self.btnregresar.setObjectName("btnregresar")
        self.verticalLayout_7.addWidget(self.btnregresar)
        self.btnsiguiente = QtWidgets.QPushButton(self.widget_4)
        self.btnsiguiente.setObjectName("btnsiguiente")
        self.verticalLayout_7.addWidget(self.btnsiguiente)
        self.horizontalLayout.addWidget(self.widget_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelreproductor_3.setText(_translate("MainWindow", "Calificacion:"))
        self.btnregresar.setText(_translate("MainWindow", "Regresar"))
        self.btnsiguiente.setText(_translate("MainWindow", "Siguiente"))
