# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Ariff\Documentos\Visual Codex\Proyecto uni\proyecto lenguaje expresivo\ventanas\instruccionesventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_acercaapp(object):
    def setupUi(self, acercaapp):
        acercaapp.setObjectName("acercaapp")
        acercaapp.resize(756, 453)
        self.centralwidget = QtWidgets.QWidget(acercaapp)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background:rgb(116, 116, 116)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("font: 63 24pt \"Lucida Sans\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("\n"
"font: 13pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setStyleSheet("font: 11pt \"Arial Rounded MT Bold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btnempezarsw = QtWidgets.QPushButton(self.frame_3)
        self.btnempezarsw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnempezarsw.setObjectName("btnempezarsw")
        self.horizontalLayout_2.addWidget(self.btnempezarsw)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame)
        acercaapp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(acercaapp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 21))
        self.menubar.setObjectName("menubar")
        self.menuAplicacion = QtWidgets.QMenu(self.menubar)
        self.menuAplicacion.setObjectName("menuAplicacion")
        self.menuRegresar = QtWidgets.QMenu(self.menubar)
        self.menuRegresar.setObjectName("menuRegresar")
        acercaapp.setMenuBar(self.menubar)
        self.actionSalir = QtWidgets.QAction(acercaapp)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAcerca_de_la_app = QtWidgets.QAction(acercaapp)
        self.actionAcerca_de_la_app.setObjectName("actionAcerca_de_la_app")
        self.back = QtWidgets.QAction(acercaapp)
        self.back.setObjectName("back")
        self.menuAplicacion.addAction(self.actionSalir)
        self.menuRegresar.addAction(self.back)
        self.menubar.addAction(self.menuAplicacion.menuAction())
        self.menubar.addAction(self.menuRegresar.menuAction())

        self.retranslateUi(acercaapp)
        QtCore.QMetaObject.connectSlotsByName(acercaapp)

    def retranslateUi(self, acercaapp):
        _translate = QtCore.QCoreApplication.translate
        acercaapp.setWindowTitle(_translate("acercaapp", "MainWindow"))
        self.label_2.setText(_translate("acercaapp", "Instrucciones"))
        self.label.setText(_translate("acercaapp", "En este proyecto se presentarán algunos textos los cuales en los cuales se le \n"
" pedirá al usuario la lectura de estos.\n"
" El programa te presentara 2 opciones, una es escuchar el audio como debe ser leído\n"
" y la otra opción de grabar el audio. Cuando termines de grabar el audio PRESIONA F4 \n"
" para detener la grabación.  Puedes grabar el audio las veces que quieras, \n"
"el programa utilizara siempre la última grabación. "))
        self.label_3.setText(_translate("acercaapp", "Cuando estes listo, presiona el boton \"EMPEZAR\""))
        self.btnempezarsw.setText(_translate("acercaapp", "Empezar"))
        self.menuAplicacion.setTitle(_translate("acercaapp", "Aplicacion"))
        self.menuRegresar.setTitle(_translate("acercaapp", "Regresar"))
        self.actionSalir.setText(_translate("acercaapp", "Salir"))
        self.actionAcerca_de_la_app.setText(_translate("acercaapp", "Acerca de la app"))
        self.back.setText(_translate("acercaapp", "Inicio"))
